apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: php-apache
  namespace: testmonitoring
  labels:
    deploymentName: php-apache
spec:
  scaleTargetRef:
    kind: deployment
    name: php-apache
  pollingInterval: 2  # Optional. Default: 30 seconds
  cooldownPeriod:  30 # Optional. Default: 300 seconds
  minReplicaCount: 1   # Optional. Default: 0
  maxReplicaCount: 5 # Optional. Default: 100
  triggers:
  - type: prometheus
    metadata:
      # Required
      serverAddress: http://prometheus-kube-prometheus-prometheus.testmonitoring:9090
      metricName: access_frequency
      threshold: '700'
      query: http_requests_total{instance="php-apache:80", job="apache"}
